.DEFAULT_GOAL := test

.PHONY: clean help migrate quality local-requirements requirements test validate html_coverage

help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo "  clean                      delete generated byte code and coverage reports"
	@echo "  help                       display this help message"
	@echo "  html_coverage              generate and view HTML coverage report"
	@echo "  migrate                    apply database migrations"
	@echo "  quality                    run PEP8 and Pylint"
	@echo "  requirements               install requirements for local development"
	@echo "  test                       run tests and generate coverage report"
	@echo "  validate                   run tests and quality checks"
	@echo ""

clean:
	find . -name '*.pyc' -delete
	coverage erase
	rm -rf assets

local-requirements:
	pip install -qr requirements/local.txt --exists-action w

requirements:
	pip install -qr requirements.txt --exists-action w

test: clean
	coverage run ./manage.py test django_sites_extensions --settings=django_sites_extensions.settings.test
	coverage report

quality:
	pep8 --config=.pep8 django_sites_extensions *.py
	pylint --rcfile=pylintrc django_sites_extensions *.py

validate: test quality

migrate:
	python manage.py migrate

html_coverage:
	coverage html && open htmlcov/index.html
